name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        - name: Install
          working-directory: ./frontend
          run: npm install
        - name: Build
          working-directory: ./frontend
          run: npm run build
        - name: Upload dist
          uses: actions/upload-pages-artifact@v1
          with:
            path: './frontend/dist'
        - name: Deploy
          uses: actions/deploy-pages@v1