name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install and build
        working-directory: frontend
        run: |
          npm ci
          npm run build
      - name: Set up Pages
        uses: actions/configure-pages@v3
      - name: Upload dist
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./frontend/dist"
      - name: Deploy
        uses: actions/deploy-pages@v1