name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: actions/deploy-pages@v1
        with:
          folder: ./frontend/dist